---
# The config file with its defaults

# What type of book files you would like to download
download_type: .epub3.images
# The number of seconds to wait before downloading the next file
download_delay: 2
# Whether to re-download updated books that already exist
update_previously_downloaded: false
# The URL to pull the RSS feed from PG
rss_feed_url: https://www.gutenberg.org/cache/epub/feeds/today.rss
# The URL to pull the XML catalog from PG
gutenberg_xml_url: https://www.gutenberg.org/cache/epub/feeds/pgmarc.xml.gz
# The URL to pull files from PG
gutenberg_mirror_url: https://www.gutenberg.org/ebooks/


